### ISSUE TITLE
curlpp library on Ubuntu 16.04

### ISSUE THREAD

**Issue by iliemihai** [Dissfall/Instagram-cpp#1]
I found an issue when compiling an example.cpp file and linking libinslib.so with curlpp library on Ubuntu 16.04. It seems that the version of curlpp library was not the correct one. In order to solve the problem I found the solution: 
```
$ sudo apt-get remove libcurlpp0
$ cd [wherever]
$ git clone https://github.com/jpbarrette/curlpp.git
$ cd curlpp
$ cmake .
$ sudo make install
$ cd [back to our library]
$ make clean
$ make
```

**Comment by Dissfall** [comment]
Hi @iliemihai ! Thank you very much for your issue. Forgive me for not responding right away. 
By specifying curlpp as a dependency, I meant installing this particular package (jpbarrette/curlpp). In the new commit https://github.com/Dissfall/Instagram-cpp/commit/e5955eff03fd67b73415edf5279912c87cd0bd59, Readme was edited with a detailed description of the curlpp installation for Ubuntu proposed by you and the installation description for openSUSE
